
package subsetsum;

public class SubsetSum {

  public static void main(String[] args) {
  
    int sum = 5;
    int[] set = {1,2,3};
    boolean[][] subsetsum = new boolean[set.length+1][sum+1];
    subsetsumdp(set,subsetsum,sum);
    System.out.println(subsetsum[set.length][sum]);
  }
  
  public static void subsetsumdp(int[] set,boolean[][]subsetsum,int sum){
    
    //the sum of 0 can be generated by any set
    for(int i=0;i<=set.length;i++)
      subsetsum[i][0] = true;
    
    //the sum is not zero and set is empty
    for(int i=1;i<sum+1;i++)
      subsetsum[0][i]=false;
    
    //building subsettable
    for(int i=1;i<=set.length;i++){
      for(int j=0;j<sum+1;j++){
        
        if(set[i-1]>j)
          subsetsum[i][j] = subsetsum[i-1][j];
        else{
           int diff = j - set[i-1];
           boolean res1= subsetsum[i-1][diff];
           boolean res2 = subsetsum[i-1][j];
          boolean result = res1||res2;
          subsetsum[i][j] = result;
        }
          
        
      }
    }
    
  }
  
  
}
